app/controllers/admin/products_controller.rb, app/views/admin/_header.html.erb, app/views/admin/dashboard/index.html.erb, app/views/admin/products/_product.html.erb, app/views/admin/products/index.html.erb, app/views/layouts/admin.html.erb, config/routes.rb, package.json, spec/request/admin/dashboard_spec.rb, spec/request/admin/products_spec.rb, tailwind.config.js, yarn.lock
=> Add products index to admin panel

app/assets/stylesheets/application.tailwind.css, app/assets/stylesheets/components/typography.css, app/controllers/admin/products_controller.rb, app/helpers/product_helper.rb, app/models/product.rb, app/views/admin/product_categories/index.html.erb, app/views/admin/products/_product.html.erb, app/views/admin/products/index.html.erb, app/views/admin/products/new.html.erb, app/views/admin/products/show.html.erb, app/views/layouts/admin.html.erb, config/routes.rb, spec/request/admin/products_spec.rb, tailwind.config.js
=> (feature): add admin product show page, with available colors

app/models/product.rb, app/views/admin/products/show.html.erb
=> (feature): admin product show page, with available sizes

app/views/admin/_header.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_header.html.erb
=> (fix): change color links

spec/factories/option_values.rb, spec/factories/options.rb, spec/factories/product_option_values.rb, spec/factories/product_options.rb, spec/lib/database_seeds/dummy/product_categories_seed_spec.rb, spec/lib/database_seeds/dummy/product_options_seed_spec.rb, spec/models/product_option_value_spec.rb, spec/models/product_spec.rb, spec/rails_helper.rb
Update rspec coverage to 100%:
=> (feat): update rspec coverage to 100%

app/views/devise/passwords/edit.html.erb, app/views/devise/registrations/edit.html.erb, config/environments/development.rb
=> (feat): update forgot password page

app/controllers/products_controller.rb, app/views/products/_product.html.erb, app/views/products/_product_placeholder.html.erb, app/views/products/index.html.erb, app/views/products/index.turbo_stream.erb, spec/request/products_spec.rb
=> (feat): add turbo_pagination to store

app/assets/stylesheets/application.tailwind.css, app/views/admin/_header.html.erb
=> STROM_F (feat): add active link class to headers

app/controllers/products_controller.rb, app/javascript/controllers/checkbox_family_controller.js, app/views/products/_store_filter.html.erb
=> STROM_F (feat): add nested checkbox select

app/assets/stylesheets/application.tailwind.css, app/assets/stylesheets/components/drawer.css, app/views/shared/_header.html.erb
=> STORM_F (feat): add drawer cart to header

app/assets/stylesheets/components/flash.css, app/controllers/admin/base_controller.rb, app/controllers/admin/product_categories_controller.rb, app/controllers/admin/products_controller.rb, app/helpers/admin/product_helper.rb, app/javascript/controllers/flash_controller.js, app/javascript/controllers/index.js, app/views/admin/shared/_flash.html.erb, app/views/layouts/admin.html.erb, spec/helpers/admin/product_helper_spec.rb, spec/request/admin/product_categories_spec.rb, spec/request/admin/products_spec.rb
=> STORM_B (feat): add flash meessage to admin panel

app/controllers/admin/product_categories_controller.rb, app/views/admin/product_categories/_product_category.html.erb, app/views/admin/product_categories/edit.html.erb, app/views/admin/product_categories/index.html.erb, app/views/admin/products/_product.html.erb, config/routes.rb, spec/request/admin/product_categories_spec.rb
=> STORM_B (feat): add edit admin category page

app/controllers/admin/product_categories_controller.rb, app/javascript/controllers/flash_controller.js, app/views/admin/product_categories/_product_category.html.erb, config/routes.rb, spec/request/admin/product_categories_spec.rb
=> STORM_B (feat): add destroy action to product category in admin panel

app/controllers/admin/product_categories_controller.rb, app/controllers/admin/products_controller.rb, app/views/admin/products/_product.html.erb, app/views/admin/products/edit.html.erb, app/views/admin/products/index.html.erb, config/routes.rb, spec/request/admin/product_categories_spec.rb, spec/request/admin/products_spec.rb
=> STORM_F (feat): add actrion destroy and edit to products in admin panel

app/assets/stylesheets/application.tailwind.css, app/controllers/admin/products_controller.rb, app/helpers/admin/product_helper.rb, app/javascript/controllers/index.js, app/javascript/controllers/nested_form_controller.js, app/javascript/controllers/toggler_controller.js, app/models/product.rb, app/views/admin/products/_form.html.erb, app/views/admin/products/_product_option_color_values_form.erb, app/views/admin/products/_product_option_size_values_form.erb, package.json, spec/factories/options.rb, spec/helpers/admin/product_helper_spec.rb, spec/request/admin/products_spec.rb, yarn.lock
=> STORM_B (feat): add options for creating new product in admin page

app/controllers/products_controller.rb, app/helpers/product_helper.rb, app/javascript/controllers/accordion_controller.js, app/javascript/controllers/index.js, app/views/products/_suggest_products.html.erb, app/views/products/show.html.erb, spec/request/products_spec.rb
@Shabaldas FYI! There is problem with tailwinds width property and breakpoints. Sometimes these styles don't apply. Maybe it's issue with tailwinds config. Could you please check it?
=> Draft: Storm_F[8]:Add product details

app/helpers/product_helper.rb, app/javascript/controllers/index.js, app/javascript/controllers/selected_size_controller.js, app/models/product.rb, app/views/products/show.html.erb, spec/helpers/product_helper_spec.rb
=> STORM_B (feat): change price when another size selected in product show

app/controllers/carts/cart_items_controller.rb, app/helpers/admin/product_helper.rb, app/helpers/product_helper.rb, app/views/admin/product_categories/_form.html.erb, app/views/admin/products/_form.html.erb, app/views/products/_form.html.erb, app/views/products/_store_filter.html.erb, spec/helpers/admin/product_helper_spec.rb, spec/helpers/product_helper_spec.rb, spec/request/admin/products_spec.rb
Change product category count in parent category.
Add new methods for select product category and product in admin panel.
=> STORM_B (feat): Change category count, update category helper for select

app/javascript/controllers/dropzone_controller.js, app/javascript/controllers/index.js, app/javascript/controllers/print_model_colors_controller.js, app/views/print_models/_form.html.erb, app/views/print_models/_upload_section.html.erb
=> STROM_F (feat): show color material, by selected material in calculator page

app/assets/stylesheets/application.tailwind.css, app/views/cart/_cart_footer_action.html.erb, app/views/cart/_empty_cart_body.erb, app/views/cart/_item_line.html.erb, app/views/cart/_side_bar_cart.html.erb
1. Add center position for placeholder
2. Fix cart styles and set mocking data for product color & dimensions:
2.1 Add close icon
2.2 Add mocking product details
2.3. Fix available height for products list
=> Customize shopping cart details

app/helpers/product_helper.rb, app/javascript/controllers/print_model_colors_controller.js, app/lib/database_seeds/dummy/options_seed.rb, app/lib/database_seeds/dummy/product_options_seed.rb, app/models/cart_item_option_value.rb, app/views/cart/_item_line.html.erb, app/views/orders/_order_cart_items.html.erb, app/views/print_models/_form.html.erb, app/views/products/_form.html.erb, spec/lib/database_seeds/dummy/product_options_seed_spec.rb
Adaptize selected color, and values in cart
=> STORM_F (feat): Addaptize cartble select color with cart item

app/assets/stylesheets/application.tailwind.css, app/assets/stylesheets/components/metrics.css, app/controllers/admin/dashboard_controller.rb, app/controllers/admin/orders_controller.rb, app/models/order.rb, app/views/admin/_header.html.erb, app/views/admin/dashboard/index.html.erb, app/views/admin/orders/_order.html.erb, app/views/admin/orders/index.html.erb, config/routes.rb, spec/request/admin/dashboard_spec.rb, spec/request/admin/orders_spec.rb
=> STORM_B (feat): add admin order index page

app/assets/stylesheets/application.tailwind.css, app/assets/stylesheets/components/select.css, app/assets/stylesheets/components/typography.css, app/controllers/dredd/manual_orders_controller.rb, app/javascript/controllers/select_controller.js, app/models/manual_order.rb, app/views/devise/registrations/new.html.erb, app/views/dredd/manual_orders/_form.html.erb, app/views/dredd/manual_orders/_manual_order.html.erb, app/views/dredd/manual_orders/new.html.erb, app/views/dredd/product_categories/_errors.html.erb, app/views/dredd/product_categories/_form.html.erb, app/views/dredd/products/_form.html.erb, app/views/dredd/shared/_errors.html.erb, app/views/shared/_footer.html.erb, config/routes.rb, spec/factories/manual_orders.rb, spec/request/dredd/dashboard_spec.rb, spec/request/dredd/feedback_calls_spec.rb, spec/request/dredd/manual_orders_spec.rb, spec/request/static_pages_spec.rb
=> Admin manual create

app/helpers/google_analytics_helper.rb, app/views/layouts/admin.html.erb, app/views/layouts/application.html.erb, app/views/layouts/checkout.html.erb, spec/request/dredd/dashboard_spec.rb
https://analytics.google.com/analytics/web/?hl=ru
=> STORM_B (feat): add google analytics to website

app/helpers/dredd/manual_order_helper.rb, app/views/dredd/manual_orders/_form.html.erb, app/views/dredd/manual_orders/show.html.erb, spec/helpers/dredd/manual_order_helper_spec.rb, spec/request/dredd/manual_orders_spec.rb
=> STORM_B (feat): add show action for show manual order

Gemfile, Gemfile.lock, config/initializers/sentry.rb
=> STORM_B (feat): add sentry to check errors in production

app/views/cart/_side_bar_cart.html.erb, app/views/shared/_header.html.erb
=> Products count

app/assets/stylesheets/application.tailwind.css, app/views/shared/_header.html.erb
1. Add menu burger
2. Add sidebar menu
=> Sidebar menu

app/views/dredd/_header.html.erb, app/views/shared/_header.html.erb, spec/request/dredd/dashboard_spec.rb
=> Admin burger

app/assets/images/icons_svg/attention.svg, app/controllers/application_controller.rb, app/controllers/dredd/feedback_calls_controller.rb, app/controllers/dredd/manual_orders_controller.rb, app/controllers/dredd/modeling_orders_controller.rb, app/controllers/dredd/printing_orders_controller.rb, app/controllers/dredd/product_categories_controller.rb, app/controllers/dredd/products_controller.rb, app/controllers/dredd/rendering_orders_controller.rb, app/controllers/locales_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/helpers/dredd/product_helper.rb, app/views/dredd/modeling_orders/_modeling_order.html.erb, app/views/dredd/printing_orders/_printing_order.html.erb, app/views/dredd/rendering_orders/_rendering_order.html.erb, app/views/dredd/shared/_flash.html.erb, spec/helpers/dredd/product_helper_spec.rb, spec/request/dredd/modeling_spec.rb, spec/request/dredd/printing_spec.rb, spec/request/dredd/rendering_spec.rb
=> STROM_B (feat): add new types of flash messages, fix bug in admin panel

app/controllers/dredd/portfolios_controller.rb, app/controllers/modeling_orders_controller.rb, app/controllers/printing_orders_controller.rb, app/controllers/rendering_orders_controller.rb, config/environments/development.rb, config/environments/test.rb
❗❗❗ Not optimazide queries will be look like:
=> STORM_B (feat): add bullet gem configs, with query optimizations

Gemfile, Gemfile.lock, app/models/application_record.rb, app/models/feedback_call.rb, app/models/modeling_order.rb, app/models/printing_order.rb, app/models/rendering_order.rb, db/schema.rb, spec/models/feedback_call_spec.rb, spec/request/dredd/dashboard_spec.rb, spec/request/dredd/feedback_calls_spec.rb, spec/request/dredd/modeling_spec.rb, spec/request/dredd/printing_spec.rb, spec/request/dredd/rendering_spec.rb, spec/request/modeling_spec.rb, spec/request/printing_spec.rb, spec/request/rendering_spec.rb, spec/request/static_pages_spec.rb
Add ability to add html in message to telegram
Change message from this:
To this:
=> STORM_B Add better html preview in telegram hooks

app/controllers/dredd/accountings_controller.rb, app/controllers/dredd/manual_orders_controller.rb, app/views/dredd/accountings/monthly.html.erb, app/views/dredd/manual_orders/_form.html.erb, config/locales/en/dredd.en.yml, config/locales/uk/dredd.uk.yml, config/schedule.yml, db/migrate/20230929155428_add_end_date_to_manual_orders.rb, db/schema.rb, spec/request/dredd/manual_orders_spec.rb
=> STORM_B (feat): add end date to manual orders

Gemfile, Gemfile.lock, app/controllers/dredd/accountings_controller.rb, app/controllers/dredd/costs_controller.rb, app/models/cost.rb, app/views/dredd/accountings/_accounting_data.html.erb, app/views/dredd/accountings/_cost.html.erb, app/views/dredd/accountings/index.html.erb, app/views/dredd/accountings/monthly.html.erb, app/views/dredd/costs/_form.html.erb, config/locales/en/dredd.en.yml, config/routes.rb, db/migrate/20230929170413_create_costs.rb, db/schema.rb, spec/request/dredd/accountings_spec.rb
=> STORM_B (feat): add cost model to accounting page

app/views/dredd/manual_orders/_manual_order.html.erb, app/views/dredd/manual_orders/index.html.erb, spec/request/dredd/manual_orders_spec.rb
=> STORM_F (feat): change manual orders in admin panel, Anton remarks

app/assets/stylesheets/application.tailwind.css, app/controllers/modeling_orders_controller.rb, app/views/modeling_orders/lazy_index.html.erb, app/views/shared/_big_picture_placeholder.html.erb, app/views/shared/_long_placeholder.html.erb, app/views/shared/_title_placeholder.html.erb, app/views/shared/_upload_form.html.erb, config/routes.rb, spec/request/modeling_spec.rb, spec/support/placeholders.rb
=> STORM_B (feat): add lazy_loading for modeling page

app/assets/stylesheets/application.tailwind.css, app/views/dredd/manual_orders/_manual_order.html.erb, app/views/dredd/manual_orders/index.html.erb
=> STORM_F (feat): add Annton improvment

app/controllers/rendering_orders_controller.rb, app/models/rendering_order.rb, app/views/rendering_orders/lazy.html.erb, config/routes.rb, spec/request/rendering_spec.rb
=> STORM_B (feat): add lazy_loading for rendering page

app/controllers/static_pages_controller.rb, app/views/static_pages/home.html.erb, app/views/static_pages/home_lazy.html.erb, config/routes.rb, spec/request/static_pages_spec.rb
=> STORM_B (feat): add lazy_loading for home page

app/controllers/dredd/manual_orders_controller.rb, app/helpers/application_helper.rb, app/models/manual_order.rb, app/views/dredd/manual_orders/_form.html.erb, app/views/dredd/manual_orders/_manual_order.html.erb, app/views/dredd/manual_orders/index.html.erb, config/locales/en/dredd.en.yml, config/locales/uk/dredd.uk.yml, db/migrate/20231011172050_add_workflow_statuses_to_manual_orders.rb, db/schema.rb, spec/factories/manual_orders.rb, spec/request/dredd/manual_orders_spec.rb
=> STROM_B (feat): add workflow status to manual orders

app/assets/images/icons_svg/3d_modeling_icon.svg, app/assets/images/icons_svg/3d_printing_icon.svg, app/assets/images/icons_svg/3d_rendering_icon.svg, app/views/printing_orders/index.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_header.html.erb, app/views/shared/_portfolio.html.erb, app/views/static_pages/home.html.erb, app/views/static_pages/home_lazy.html.erb
1. Fix portfolio section shadow
2. Set proper position for minimal price of order
3. Align elements in header
4. Remove icons shadow
5. Fix image height of portfolio items on mobile
=> STORM_F[18]: UI fixes

app/controllers/dredd/manual_orders_controller.rb, app/controllers/dredd/users_controller.rb, app/helpers/dredd/manual_order_helper.rb, app/lib/database_seeds/dummy/workers_seed.rb, app/lib/database_seeds/main.rb, app/models/manual_order.rb, app/models/worker.rb, app/views/dredd/manual_orders/_form.html.erb, app/views/dredd/users/_worker.html.erb, app/views/dredd/users/index.html.erb, config/locales/en/dredd.en.yml, config/locales/uk/dredd.uk.yml, db/migrate/20231017201206_create_workers.rb, db/migrate/20231017211240_add_worker_references_to_manual_orders.rb, db/migrate/20231017212755_remove_modellers_manual_orders.rb, db/schema.rb, spec/factories/workers.rb, spec/lib/database_seeds/dummy/workers_seed_spec.rb, spec/models/worker_spec.rb, spec/request/dredd/manual_orders_spec.rb, spec/request/dredd/users_spec.rb
=> STORM_B (feat): add worker model to project

app/controllers/dredd/accountings_controller.rb, app/helpers/dredd/accounting_helper.rb, app/views/dredd/accountings/_accounting_data.html.erb, app/views/dredd/accountings/_cost.html.erb, app/views/dredd/accountings/_reward_data.html.erb, app/views/dredd/accountings/index.html.erb, app/views/dredd/accountings/monthly.html.erb, app/views/dredd/costs/_form.html.erb, config/locales/en/dredd.en.yml, config/locales/uk/dredd.uk.yml
=> STROM_B (feat): add reward and profit to accounting

app/controllers/dredd/manual_orders_controller.rb, app/helpers/dredd/manual_order_helper.rb, app/models/manual_order.rb, app/views/dredd/manual_orders/_form.html.erb, app/views/dredd/manual_orders/_manual_order.html.erb, app/views/dredd/manual_orders/index.html.erb, config/locales/en/dredd.en.yml, config/locales/uk/dredd.uk.yml, db/migrate/20231018105307_add_need_to_call_client_to_manual_orders.rb, db/schema.rb, spec/request/dredd/manual_orders_spec.rb
=> STORM_B (feat): added need_to_call_client status to manual order

app/assets/stylesheets/application.tailwind.css, app/views/dredd/modeling_orders/_form.html.erb, app/views/dredd/printing_orders/_form.html.erb, app/views/dredd/rendering_orders/_form.html.erb, config/locales/en/dredd.en.yml, config/locales/uk/dredd.uk.yml
=> STROM_B (feat): add link_to models to admin interface

app/models/manual_order.rb, app/views/dredd/manual_orders/edit.html.erb, spec/models/manual_order_spec.rb, spec/request/dredd/manual_orders_spec.rb
=> STORM_B (feat): add worker validation to manual orders on update

app/controllers/dredd/manual_orders_controller.rb, app/models/user.rb, app/policies/admin_policy.rb, app/views/dredd/_header.html.erb, app/views/dredd/dashboard/index.html.erb, app/views/dredd/manual_orders/_manual_order.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_header.html.erb, spec/factories/users.rb, spec/models/user_spec.rb
=> (feat): add manager interface to admin panel

Gemfile, Gemfile.lock, app/views/layouts/admin.html.erb, app/views/layouts/application.html.erb, app/views/layouts/checkout.html.erb, config/initializers/canonical_rails.rb
=> (feat): add canonical gem to project

app/controllers/dredd/manual_orders_controller.rb, app/views/dredd/manual_orders/_form.html.erb, app/views/dredd/manual_orders/index.html.erb, config/locales/en/dredd.en.yml, config/locales/uk/dredd.uk.yml, db/migrate/20231217175655_add_individual_entrepreneur_accouting_to_manual_orders.rb, db/schema.rb, spec/factories/costs.rb, spec/request/dredd/costs_spec.rb, spec/request/dredd/manual_orders_spec.rb
=> STORM_B (feat): add individual_entrepreneur_accountings to manual orders

app/lib/database_seeds/main.rb, app/lib/database_seeds/real/cities_seed.rb, spec/lib/database_seeds/real/cities_seed_spec.rb
This pull request includes changes to the database seeding files. The changes are primarily focused on adding new city data for different regions in Ukraine. 
The most important changes are:
* [`app/lib/database_seeds/main.rb`](diffhunk://#diff-1109c7e9abaad53ac8c550a4c0c219b8f1f307fe9849e5b8f5c3ff4a27fe1ac9R16-R24): Added calls to new methods that seed the database with city data for different regions in Ukraine.
* [`app/lib/database_seeds/real/cities_seed.rb`](diffhunk://#diff-2e9a01ff9f16f186afbd501b0e3e5d2983cc921b2074166e4749cfacd231c1acR31-R238): Added new methods for each region in Ukraine, each of which seeds the database with city data for that region.
* [`spec/lib/database_seeds/real/cities_seed_spec.rb`](diffhunk://#diff-042892c449335fa8a5dd5e0dc9118671353b2c81f0273d300bfd41a992 …
=> (feat): add west regions cities to DB

app/views/layouts/admin.html.erb, app/views/layouts/application.html.erb, app/views/layouts/checkout.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_header.html.erb, app/views/static_pages/home_lazy.html.erb
This pull request includes changes aimed at improving accessibility and localization of the application. The most significant changes involve adding dynamic language attributes to the `head` tags in several layout files, modifying links to point to the production site in non-development environments, adding alternative text to image tags, and wrapping an image tag in a `picture` tag.
Localization:
* [`app/views/layouts/admin.html.erb`](diffhunk://#diff-9fc91735fae00b113814072ed1438c53d5cf484a66c6710bc1f94f6e7d48a3f1L3-R3): Added dynamic language attribute to the `head` tag.
* [`app/views/layouts/application.html.erb`](diffhunk://#diff-f43fe075643e681b2c01c2f853bb0c4299d135b47fcbd4da96890d521c49e3ebL3-R3): Added dynamic language attribute to the `head` tag.
* …
=> (feat): small html fix

app/helpers/application_helper.rb, app/views/cart/_empty_cart_body.erb, app/views/layouts/admin.html.erb, app/views/layouts/application.html.erb, app/views/layouts/checkout.html.erb, app/views/rendering_orders/index.html.erb, app/views/rendering_orders/lazy.html.erb, app/views/rendering_orders/rendering_in_your_city.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_header.html.erb, app/views/shared/_modal.html.erb, app/views/shared/_portfolio.html.erb, app/views/shared/_upload_form.html.erb, app/views/static_pages/_question_form.html.erb, app/views/static_pages/home_lazy.html.erb, app/views/static_pages/printing/_dlp_tab.html.erb, app/views/static_pages/printing/_fdm_tab.html.erb, app/views/static_pages/printing/_sla_tab.html.erb
This pull request primarily focuses on improving the accessibility of the application by adding alternative text to images and button names for better screen reader support. It also includes the commenting out of the Google Analytics script in various layout files. 
The changes can be grouped into two main categories:
Accessibility Improvements:
* [`app/helpers/application_helper.rb`](diffhunk://#diff-5f3fc5e3977d242572aa1d08551f5eb557de0ccaff30370838ee9df5386ea0daL17-R22): Added alternative text to flag images and names to language switch buttons for better screen reader support.
* Various files including `app/views/cart/_empty_cart_body.erb`, `app/views/rendering_orders/index.html.erb`, `app/views/shared/_footer.html.erb`, and others: Added alternative text to images for better screen …
=> (feat): add alt attribute to existing images

app/lib/database_seeds/dummy/clients_seed.rb, app/lib/database_seeds/dummy/manual_orders_seed.rb, app/lib/database_seeds/main.rb, app/models/client.rb, app/models/manual_order.rb, db/migrate/20240222064739_create_clients.rb, db/migrate/20240222070121_add_client_references_to_manual_orders.rb, db/schema.rb, spec/factories/clients.rb, spec/lib/database_seeds/dummy/clients_seed_spec.rb, spec/lib/database_seeds/dummy/manual_orders_seed_spec.rb, spec/models/client_spec.rb, spec/models/manual_order_spec.rb
1. Create new table " Client" with relation:
-   1. first_name: string
-   2. last_name: string
-   3. email: string
-   4. phone_number: string
2. Add accociation to many manual_order
3. Add seed for Client
4. Add rspec test and run rubocop
=> STORM_B: add new table client and add relation

app/controllers/application_controller.rb, app/controllers/profiles_controller.rb, app/policies/user_policy.rb, app/views/profiles/_form.html.erb, spec/policies/user_policy_spec.rb, spec/request/profile_spec.rb
This pull request introduces changes primarily focused on enhancing user authorization and improving the handling of user profiles. The most significant changes include the addition of a new `UserPolicy` class to manage user access, modifications to the `ProfilesController` to incorporate user authorization, and updates to the `profiles/_form.html.erb` view to reflect these changes. Additionally, the `application_controller.rb` has been updated to include new flash types, and tests have been added to verify the new functionalities.
User Authorization:
* [`app/policies/user_policy.rb`](diffhunk://#diff-e8babf74fdfb1b1c4919dcff37b105f1aa5ee47e9897093dd42c0640332fe98fR1-R18): A new `UserPolicy` class has been added which includes an `access?` method. This method checks if the current user is …
=> STORM_B (feat): add policy for user

app/controllers/dredd/clients_controller.rb, app/models/client.rb, app/views/dredd/clients/index.html.erb, app/views/dredd/manual_orders/index.html.erb, config/locales/en/dredd.en.yml, config/locales/uk/dredd.uk.yml
Add search in client admin page:
1.  First name, last name, full_name
2. nickname
3. phone number
=> STORM_B: Add search in client page

app/lib/database_seeds/dummy/clients_seed.rb, app/models/client.rb, app/views/dredd/clients/_client.html.erb, app/views/dredd/clients/index.html.erb, spec/lib/database_seeds/dummy/clients_seed_spec.rb
This pull request primarily focuses on enhancing the client data generation and validation in the `ClientsSeed` and `Client` classes respectively. The changes include an increase in the number of dummy clients created in the seeding process and the addition of new validation rules for the phone number attribute in the `Client` model.
Changes in client data generation:
* [`app/lib/database_seeds/dummy/clients_seed.rb`](diffhunk://#diff-5a555fb43b402b2cdb3946a5d9345a13f9c0ca54f849503dc1be44e63ac4979fL9-R9): The `execute` method in the `ClientsSeed` class has been modified to generate 25 dummy clients instead of the previous 5. This change will provide more data for testing and development purposes.
Changes in client data validation:
* …
=> STROM_B (feat): add phone validation to clinets

app/views/shared/_header.html.erb, config/routes.rb
=> STORM_B (feat): fix not used routes

db/migrate/20240228103330_remove_unique_constraint_from_clients_phone_number.rb, db/schema.rb
Add ability to cteate client without phone number
=> STORM_B: add migration to delet unic from phone number in client

app/models/manual_order.rb, app/views/dredd/clients/index.html.erb, app/views/dredd/manual_orders/index.html.erb, config/locales/en/dredd.en.yml, config/locales/uk/dredd.uk.yml
Add ability to search first name, last name or full name in manual order admin page.
Add ability to search phone number in manual order admin page.
=> STORM_B: Add search for manual order and fix locale

lib/tasks/client_find_or_create.rake, spec/task/client_find_or_create_spec.rb
Add rake task for create new Client form Manual Order
=> STORM_B: add rake task for: find or create Client from ManualOrder

app/controllers/dredd/dashboard_controller.rb, app/controllers/dredd/manual_orders_controller.rb, app/views/dredd/_header.html.erb, app/views/dredd/dashboard/index.html.erb, app/views/dredd/manual_orders/_manual_order.html.erb, app/views/dredd/manual_orders/edit.html.erb, config/locales/en/dredd.en.yml, config/locales/uk/dredd.uk.yml
This pull request primarily focuses on enhancing the client management in the Dredd application. The changes include adding a client count to the dashboard, modifying the manual orders controller to include client data, and updating the manual orders view to display client-specific information. Additionally, the header navigation has been updated to include links to the clients and workers pages, and language localization files have been updated to include translations for "Clients".
Client Management Enhancements:
* [`app/controllers/dredd/dashboard_controller.rb`](diffhunk://#diff-6b6176237ac38e8ed903b031f3ddc57c4dc10d266a20bfa846280f3ba54041b7R13): Added a count of clients to the dashboard data.
* [`app/controllers/dredd/manual_orders_controller.rb`](diffhunk://#diff-cada2222d0f82ca1de7 …
=> STORM_B (feat): add small improvments for admin page

app/assets/stylesheets/application.tailwind.css, app/assets/stylesheets/components/select.css, app/assets/stylesheets/components/toggle-switch.css, app/views/dredd/manual_orders/_client_form.html.erb, app/views/dredd/manual_orders/_form.html.erb, app/views/dredd/manual_orders/new_manual_order.html.erb, app/views/dredd/manual_orders/new_manual_order_from_client.html.erb
Change layout of manual order and manual order from client
Make both form responsive
=> Create order form layout

app/controllers/dredd/clients_controller.rb, app/views/dredd/clients/_manual_order.html.erb, app/views/dredd/clients/index.html.erb, app/views/dredd/clients/show.html.erb
This pull request primarily focuses on enhancing the user interface and improving data sorting in the Dredd application. The two main changes are the reordering of manual orders in the `clients_controller.rb` and the addition of more information to the manual order link in the `_manual_order.html.erb` view.
User Interface Enhancements:
* [`app/views/dredd/clients/_manual_order.html.erb`](diffhunk://#diff-590c17e1c48fbcf5d445b0c02d793bc33bb26842814a06b3f0b51edfb3d795e8L3-R20): The link to the manual order edit page now includes more information. This includes the `print_code`, `total_price` in UAH, and a comment if it exists. The elements are arranged in a flex container with space between items for better readability.
Data Sorting Improvements:
* …
=> (feat): add small UI improvments to admin interface

app/javascript/controllers/index.js, app/javascript/controllers/select_client_controller.js, app/views/dredd/manual_orders/_client_form.html.erb, app/views/dredd/manual_orders/_form.html.erb
This pull request primarily focuses on improving the user interface and functionality of the client selection process in the manual orders form. The changes include the addition of a new JavaScript controller for client selection, changes to the form layout, and the registration of the new controller in the application's JavaScript index file.
Here are the key changes:
New JavaScript Controller:
* [`app/javascript/controllers/select_client_controller.js`](diffhunk://#diff-89524497ae633510e632e2ec5af65bb97ac630ae9461428580ec462774b0dc1dR1-R20): A new JavaScript controller has been added to handle the functionality of updating a link with client details based on the client selected in the form. This controller listens to changes in the client selection and updates the link accordingly.
Form …
=> STORM_F (feat): add link to client page
